name: Renovate
on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - develop
            - main
jobs:
    renovate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Self-hosted Renovate
              uses: renovatebot/github-action@v40.3.4
              with:
                  token: ${{ secrets.RENOVATE_TOKEN }}
              env:
                  LOG_LEVEL: "debug"
                  RENOVATE_EXTRA_FLAGS: "--autodiscover"
